spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  transaction:
    default-timeout: 60s

  restdocs:
    uris:
      scheme: http
      host: localhost
      port: 8080

logging:
  level:
    com.project200.undabang: debug  # 애플리케이션 로그
    org.hibernate.SQL: debug    # SQL 쿼리 로깅
    org.hibernate.orm.jdbc.bind: trace # SQL 파라미터 바인딩 로깅 (Hibernate 6.x)

cors:
  allowed-origins:
    - http://localhost:3000