version: "3"

services:
  server-dev:
    image: "825773631552.dkr.ecr.ap-northeast-2.amazonaws.com/undabang/dev-server-repository:latest"
    restart: always
    container_name: "server-dev"
    ports:
      - "8090:8080"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge