version: "3"

services:
  server-prod-blue:
    image: "825773631552.dkr.ecr.ap-northeast-2.amazonaws.com/undabang/prod-server-repository:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    container_name: "server-prod-blue"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DEPLOYMENT_ENV=blue
    networks:
      - server-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/system-monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "deployment.environment=blue"
      - "deployment.port=8080"
      - "service.name=undabang-server"

networks:
  server-network:
    driver: bridge