version: "3.3"

services:
  server-prod:
    image: "867637277997.dkr.ecr.ap-northeast-2.amazonaws.com/undabang/prod-server-repository:latest"
    container_name: "server-prod"
    ports:
      - "8080:8080"
    networks:
      - server-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/system-monitor/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # 운영 서버는 스왑메모리 영역에 최대한 가지 않도록 설정

    environment:
      - JAVA_TOOL_OPTIONS=-Xms400m -Xmx500m -XX:MaxMetaspaceSize=128m

    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 512M

networks:
  server-network:
    driver: bridge