package com.project200.undabang.common.service;

import com.project200.undabang.common.context.UserContextHolder;
import com.project200.undabang.common.entity.Picture;
import com.project200.undabang.common.entity.dto.PictureUploadParameters;
import com.project200.undabang.common.repository.PictureRepository;
import com.project200.undabang.common.web.exception.CustomException;
import com.project200.undabang.common.web.exception.ErrorCode;
import com.project200.undabang.common.web.exception.S3UploadFailedException;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.web.multipart.MultipartFile;
import org.testcontainers.containers.localstack.LocalStackContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.CreateBucketRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.S3Exception;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@Testcontainers
@SpringBootTest
public class PictureServiceIntegrationTest {

    @Container
    static LocalStackContainer localStack = new LocalStackContainer(
            DockerImageName.parse("localstack/localstack:latest"))
            .withServices(LocalStackContainer.Service.S3)
            .withEnv("DEFAULT_REGION", "ap-northeast-2");
    @Autowired
    private PictureService pictureService;
    @Autowired
    private PictureRepository pictureRepository;
    @Autowired
    private S3Service s3Service;
    @Autowired
    private S3Client s3Client;
    @Autowired
    private EntityManager entityManager;
    @Value("${app.s3.bucket-name}")
    private String BUCKET_NAME;
    @MockitoSpyBean
    private S3Service s3ServiceSpy;
    @MockitoSpyBean
    private PictureRepository pictureRepositorySpy;

    @DynamicPropertySource
    static void overrideProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.cloud.aws.s3.endpoint", () -> localStack.getEndpointOverride(LocalStackContainer.Service.S3).toString());
        registry.add("spring.cloud.aws.credentials.access-key", localStack::getAccessKey);
        registry.add("spring.cloud.aws.credentials.secret-key", localStack::getSecretKey);
        registry.add("spring.cloud.aws.region.static", localStack::getRegion);
    }

    @BeforeEach
    void setUp() {
        reset(s3ServiceSpy, pictureRepositorySpy);

        pictureRepository.deleteAllInBatch();

        S3Client s3 = S3Client.builder()
                .endpointOverride(localStack.getEndpointOverride(LocalStackContainer.Service.S3))
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(localStack.getAccessKey(), localStack.getSecretKey())))
                .region(Region.of(localStack.getRegion()))
                .build();
        try {
            s3.createBucket(CreateBucketRequest.builder().bucket(BUCKET_NAME).build());
        } catch (S3Exception e) { /* 이미 존재하면 무시 */ }

        s3.listObjectsV2(ListObjectsV2Request.builder().bucket(BUCKET_NAME).build())
                .contents().forEach(obj -> s3Service.deleteImage(obj.key()));
        s3.listObjectsV2(ListObjectsV2Request.builder().bucket(BUCKET_NAME).prefix("trash/").build())
                .contents().forEach(obj -> s3Service.deleteImage(obj.key()));
    }

    @Nested
    @DisplayName("사진 업로드 통합 테스트 (성공 케이스)")
    class UploadPictureSuccessIntegrationTests {

        @Test
        @DisplayName("성공[자동 키 생성]: S3에 파일이 업로드되고 DB에 Picture 데이터가 정상적으로 저장된다")
        void upload_WithAutoGeneratedKey_Success_Integration() {
            // given
            List<MultipartFile> fileList = List.of(
                    new MockMultipartFile("f1", "auto-key1.jpg", "image/jpeg", "c1".getBytes()),
                    new MockMultipartFile("f2", "auto-key2.png", "image/png", "c2".getBytes())
            );

            try (MockedStatic<UserContextHolder> mockedUser = mockStatic(UserContextHolder.class)) {
                when(UserContextHolder.getUserId()).thenReturn(UUID.randomUUID());

                // when
                List<Picture> result = pictureService.uploadPictureListToS3AndDB(fileList, FileType.PROFILE);

                // then
                assertThat(result).hasSize(2);
                List<Picture> savedPictures = pictureRepository.findAll();
                assertThat(savedPictures).hasSize(2);
                assertThat(savedPictures.get(0).getPictureName()).isEqualTo("auto-key1.jpg");
            }
        }

        @Test
        @DisplayName("성공[수동 키 지정]: 미리 지정된 objectKey로 S3에 파일이 업로드되고 DB에 데이터가 저장된다")
        void upload_WithPredefinedKey_Success_Integration() {
            // given
            List<PictureUploadParameters> params = List.of(
                    new PictureUploadParameters(
                            new MockMultipartFile("f1", "manual1.txt", "text/plain", "c1".getBytes()),
                            "manual/uploads/file1.txt"
                    ),
                    new PictureUploadParameters(
                            new MockMultipartFile("f2", "manual2.json", "application/json", "{}".getBytes()),
                            "manual/uploads/data.json"
                    )
            );

            // when
            List<Picture> result = pictureService.uploadPictureListToS3AndDB(params);

            // then
            assertThat(result).hasSize(2);
            List<Picture> savedPictures = pictureRepository.findAll();
            assertThat(savedPictures).hasSize(2);

            assertThat(s3Service.isFileExists("manual/uploads/file1.txt")).isTrue();
            assertThat(s3Service.isFileExists("manual/uploads/data.json")).isTrue();

            String url1 = savedPictures.stream().filter(p -> p.getPictureName().equals("manual1.txt")).findFirst().get().getPictureUrl();
            assertThat(url1).endsWith("manual/uploads/file1.txt");
        }

        @Test
        @DisplayName("성공[단일 파일]: 단일 파일이 S3에 업로드되고 DB에 정상적으로 저장된다")
        void upload_SingleFile_Success_Integration() {
            // given
            MockMultipartFile singleFile = new MockMultipartFile("picture", "single-upload.png", "image/png", "test-content".getBytes());

            try (MockedStatic<UserContextHolder> mockedUser = mockStatic(UserContextHolder.class)) {
                when(UserContextHolder.getUserId()).thenReturn(UUID.randomUUID());

                // when
                Picture result = pictureService.uploadPictureToS3AndDB(singleFile, FileType.PROFILE);

                // then
                // 1. 반환된 객체 검증
                assertThat(result).isNotNull();
                assertThat(result.getId()).isNotNull();

                // DB에 저장된 '원본 파일 이름'이 올바른지 확인
                assertThat(result.getPictureName()).isEqualTo("single-upload.png");
                // S3에 저장된 URL은 null이 아니며, .png로 끝나는지만 확인
                assertThat(result.getPictureUrl()).isNotNull().endsWith(".png");

                // 2. DB 상태 직접 검증 (더 확실한 검증)
                Optional<Picture> savedPictureOpt = pictureRepository.findById(result.getId());
                assertThat(savedPictureOpt).isPresent();
                assertThat(savedPictureOpt.get().getPictureName()).isEqualTo("single-upload.png");

                // 3. S3 상태 직접 검증
                String objectKey = s3Service.extractObjectKeyFromUrl(result.getPictureUrl());
                assertThat(s3Service.isFileExists(objectKey)).isTrue();
            }
        }


        @Test
        @DisplayName("성공[단일 수동 키]: 수동 objectKey로 S3에 업로드되고 DB에 저장된다")
        void upload_SingleFile_WithManualKey_Success_Integration() {
            MockMultipartFile singleFile = new MockMultipartFile("f", "int-manual.txt", "text/plain", "hello".getBytes());
            String manualKey = "manual/integration/int-manual.txt";

            try (MockedStatic<UserContextHolder> mockedUser = mockStatic(UserContextHolder.class)) {
                mockedUser.when(UserContextHolder::getUserId).thenReturn(UUID.randomUUID());

                Picture result = pictureService.uploadPictureToS3AndDB(singleFile, manualKey);

                assertThat(result).isNotNull();
                assertThat(result.getId()).isNotNull();
                assertThat(result.getPictureName()).isEqualTo("int-manual.txt");
                assertThat(result.getPictureUrl()).isNotNull().endsWith(manualKey);

                Optional<Picture> saved = pictureRepository.findById(result.getId());
                assertThat(saved).isPresent();
                String objectKey = s3Service.extractObjectKeyFromUrl(result.getPictureUrl());
                assertThat(s3Service.isFileExists(objectKey)).isTrue();
            }
        }

        @Test
        @DisplayName("실패: 빈 파일을 업로드하면 CustomException(PICTURE_IS_EMPTY)을 던진다")
        void upload_SingleFile_WithManualKey_Fail_WhenFileIsEmpty_Integration() {
            MockMultipartFile emptyFile = new MockMultipartFile("f", "empty.txt", "text/plain", new byte[0]);

            try (MockedStatic<UserContextHolder> mockedUser = mockStatic(UserContextHolder.class)) {
                mockedUser.when(UserContextHolder::getUserId).thenReturn(UUID.randomUUID());

                assertThatThrownBy(() -> pictureService.uploadPictureToS3AndDB(emptyFile, "manual/empty.txt"))
                        .isInstanceOf(CustomException.class)
                        .extracting("errorCode")
                        .isEqualTo(ErrorCode.PICTURE_IS_EMPTY);

                // DB에 저장된 항목이 없어야 함
                assertThat(pictureRepository.findAll()).isEmpty();
            }
        }

    }

    @Nested
    @DisplayName("사진 삭제 통합 테스트")
    class DeletePictureIntegrationTests {

        @Test
        @DisplayName("성공: S3 파일이 휴지통으로 이동하고 DB 데이터가 soft-delete 된다")
        void delete_Success_Integration() {
            // given: 테스트 데이터 생성
            // 1. Picture 엔티티 2개를 DB에 저장
            Picture pic1 = pictureRepository.save(Picture.builder().pictureUrl("http://s3.com/uploads/success1.jpg").build());
            Picture pic2 = pictureRepository.save(Picture.builder().pictureUrl("http://s3.com/uploads/success2.png").build());

            // 2. 해당 Picture에 매칭되는 실제 파일을 LocalStack S3에 업로드
            s3Service.uploadImage(new MockMultipartFile("f", "s1.jpg", "image/jpeg", "c".getBytes()), "uploads/success1.jpg");
            s3Service.uploadImage(new MockMultipartFile("f", "s2.png", "image/png", "c".getBytes()), "uploads/success2.png");

            List<Picture> pictureList = List.of(pic1, pic2);

            // when: 테스트 대상 메서드 호출
            pictureService.deletePictureFromS3AndDB(pictureList);

            // then: 결과 검증
            // 1. DB 검증: deleted_at 컬럼이 null이 아닌지 확인
            Picture deletedPic1 = pictureRepository.findById(pic1.getId()).get();
            Picture deletedPic2 = pictureRepository.findById(pic2.getId()).get();
            assertThat(deletedPic1.getPictureDeletedAt()).isNotNull();
            assertThat(deletedPic2.getPictureDeletedAt()).isNotNull();

            // 2. S3 검증: 원본 파일은 없고, 휴지통에 파일이 있는지 확인
            assertThat(s3Service.isFileExists("uploads/success1.jpg")).isFalse();
            assertThat(s3Service.isFileExists("trash/uploads/success1.jpg")).isTrue();
            assertThat(s3Service.isFileExists("uploads/success2.png")).isFalse();
            assertThat(s3Service.isFileExists("trash/uploads/success2.png")).isTrue();
        }

        @Test
        @DisplayName("실패 및 롤백: S3 이동 실패 시 DB 트랜잭션도 롤백된다")
        void delete_Fail_And_Rollback_Integration() {
            // given: 테스트 데이터 생성
            Picture pic1 = pictureRepository.save(Picture.builder().pictureUrl("http://s3.com/uploads/rollback1.jpg").build());
            Picture pic2 = pictureRepository.save(Picture.builder().pictureUrl("http://s3.com/uploads/fail-on-this.png").build()); // 여기서 실패
            s3Service.uploadImage(new MockMultipartFile("f", "r1.jpg", "image/jpeg", "c".getBytes()), "uploads/rollback1.jpg");
            s3Service.uploadImage(new MockMultipartFile("f", "fail.png", "image/png", "c".getBytes()), "uploads/fail-on-this.png");

            List<Picture> pictureList = List.of(pic1, pic2);

            // S3Service의 실제 객체를 사용하되, 특정 키에 대해서만 예외를 발생시키도록 SpyBean 설정
            doThrow(new S3UploadFailedException("강제 S3 에러"))
                    .when(s3ServiceSpy).moveImageToTrash("uploads/fail-on-this.png");

            // when & then: 예외 발생 검증
            assertThatThrownBy(() -> pictureService.deletePictureFromS3AndDB(pictureList))
                    .isInstanceOf(CustomException.class);

            // then: 롤백 결과 검증
            // 1. DB 검증: 트랜잭션이 롤백되어 deleted_at이 여전히 null인지 확인
            Picture notDeletedPic1 = pictureRepository.findById(pic1.getId()).get();
            Picture notDeletedPic2 = pictureRepository.findById(pic2.getId()).get();
            assertThat(notDeletedPic1.getPictureDeletedAt()).isNull();
            assertThat(notDeletedPic2.getPictureDeletedAt()).isNull();

            // 2. S3 검증: 수동 롤백이 동작하여 모든 파일이 원본 위치에 그대로 있는지 확인
            assertThat(s3Service.isFileExists("uploads/rollback1.jpg")).isTrue();
            assertThat(s3Service.isFileExists("trash/uploads/rollback1.jpg")).isFalse();
            assertThat(s3Service.isFileExists("uploads/fail-on-this.png")).isTrue();
        }

        @Test
        @DisplayName("성공[단일 삭제]: 단일 Picture 객체 삭제 시 S3 파일이 휴지통으로 이동하고 DB가 soft-delete 된다")
        void delete_SinglePicture_Success_Integration() {
            // given
            // 1. DB에 Picture 엔티티 저장
            Picture pic = pictureRepository.save(Picture.builder().pictureUrl("http://s3.com/uploads/single-delete.gif").build());
            // 2. LocalStack S3에 실제 파일 업로드
            s3Service.uploadImage(new MockMultipartFile("f", "single.gif", "image/gif", "c".getBytes()), "uploads/single-delete.gif");

            // when
            pictureService.deletePictureFromS3AndDB(pic);

            // then
            // 1. DB 검증: deleted_at 컬럼 확인
            entityManager.clear(); // 영속성 컨텍스트를 비워 DB에서 직접 다시 조회하도록 강제
            Picture deletedPic = pictureRepository.findById(pic.getId()).get();
            assertThat(deletedPic.getPictureDeletedAt()).isNotNull();

            // 2. S3 검증: 원본 파일 삭제 및 휴지통으로 이동 확인
            assertThat(s3Service.isFileExists("uploads/single-delete.gif")).isFalse();
            assertThat(s3Service.isFileExists("trash/uploads/single-delete.gif")).isTrue();
        }
    }
}
